language: python
python:
  - "3.9"
install:
  - pip install --user -r requirements-dev.txt
  - pip install -e .
  - pip install codecov pytest-cov
script:
  - pytest --cov=lr2d tests
after_success:
  - codecov
